import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/organisms/hero';
import MiniAbout from '../components/organisms/miniabout';
import MiniServices from '../components/organisms/miniservices';
import VisionMission from '../components/organisms/visionmission';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <MiniAbout />
        <MiniServices />
        <VisionMission />
      </main>

    </div>
  )
}

export default Home
